root@ip-172-31-46-33:/etc/nginx/sites-available# cat doorman.conf

server {
    server_name covert.davidsondesigners.com;
    access_log /var/log/nginx/covert.davidsondesigners.com.access.log;
    error_log /var/log/nginx/covert.davidsondesigners.com.error.log;

    
# The "Secret Path" for your VPN
location / {
    proxy_pass http://127.0.0.1:8080; # No trailing slash here
    proxy_http_version 1.1;
    
    # These headers are mandatory for WebSockets
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    
    # Pass the real Host and IP info
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # Stop Nginx from timing out during long VPN sessions
    proxy_read_timeout 86400s;
    proxy_send_timeout 86400s;
}
 

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/covert.davidsondesigners.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/covert.davidsondesigners.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = covert.davidsondesigners.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name covert.davidsondesigners.com;
    return 404; # managed by Certbot



    }

