[Interface]
Address = 10.0.0.1/24           # Internal IP for the server
PrivateKey = WJD+mGoEd1esWQK1vbcKc9Io9eVQRyTWMVTd+3k3CFE=  # Replace with your server's private key
ListenPort = 53              # Default WireGuard port
MTU = 1280

[Peer]
PublicKey = PH2wCI5OPyltLBmGKOkgjXeHKm1KvoZMQMi9CgON1x0=   # Replace with the client's public key
AllowedIPs = 10.0.0.2/32        # Internal IP for the client
