[Interface]
MTU = 1280
PostUp = echo "nameserver 8.8.8.8" > /etc/resolv.conf
PostDown = nmcli general reload conf  # This tells NM to take back control
Address = 10.0.0.2/24           # Internal IP for the client
PrivateKey = AN4UvWWoQ3V2NTRVG9+IWfhy6xyfK5c6H4bBfFkh3Uk=  # Replace with the client's private key
[Peer]
PublicKey = sZsLlQYmnTnOhMB4+HD+R8wbkHhZmvrTRGoJBwJf02w=   # Replace with the server's public key
Endpoint = 127.0.0.1:51820      # Replace with the server's public IP and port
AllowedIPs = 0.0.0.0/0          # Route all traffic through the VPN
#AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25        # Keep the connection alive
