#/lib/security/howdy/config.ini
[core]
data_dir = /lib/security/howdy/models
detection_notice = true
no_face_help_msg = true
device_path = /dev/video2

[video]
device_path = /dev/video2
max_height = 320
record_fps = true
certainty = 5.0
[debug]
end_report = false
