server {
    server_name davidsondesigners.com www.davidsondesigners.com;

    root /var/www/davidsondesigners.com;
    index index.php index.html index.htm;

    access_log /var/log/nginx/davidsondesigners.com.access.log;
    error_log /var/log/nginx/davidsondesigners.com.error.log;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;  # Adjust PHP version if necessary
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        #Cache appends    
        fastcgi_cache WORDPRESS;
        fastcgi_cache_valid 200 301 302 60m;
        add_header X-FastCGI-Cache $upstream_cache_status;
        
    }

    location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
    expires 30d;
    add_header Cache-Control "public, no-transform";
}

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }

    


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/davidsondesigners.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/davidsondesigners.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}


server {
    if ($host = www.davidsondesigners.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = davidsondesigners.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name davidsondesigners.com www.davidsondesigners.com;
    return 404; # managed by Certbot




}






